name: Build/Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint
  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit
  integration-test-ubuntu:
    name: Ubuntu integration tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - name: Install dependencies
        run: sudo python -m pip install tox
      - name: Run integration tests for Ubuntu
        # tests must be run as root because they configure the system
        run: sudo tox -e integration-ubuntu
  integration-test-juju-systemd-notices:
    name: Juju systemd notices integration tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@3d3eb35d73c0f326d07880d83a99876d321f823c # 1.1.0
        with:
          provider: lxd
          juju-channel: 3.1/stable
      - name: Run integration tests (juju-systemd-notices)
        run: tox run -e integration-juju-systemd-notices
