name: Build/Test

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tox
        run: pip install tox~=4.2
      - name: Run linters
        run: tox -e lint
  static:
    name: Static
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tox
        run: pip install tox~=4.2
      - name: Run static type checks (selected libs only)
        run: tox -e static
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox~=4.2
      - name: Run tests
        run: tox -e unit
  integration-test-ubuntu:
    name: Ubuntu integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # tests must be run as root because they configure the system
      - name: Install tox
        run: sudo apt install tox
      - name: Run integration tests for Ubuntu
        run: sudo tox -e integration-ubuntu
  integration-test-juju-systemd-notices:
    name: Juju systemd notices integration tests
    runs-on: ubuntu-latest
    env:
      PIP_BREAK_SYSTEM_PACKAGES: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@3d3eb35d73c0f326d07880d83a99876d321f823c # 1.1.0
        with:
          provider: lxd
          juju-channel: 3.6/stable
      - name: Run integration tests (juju-systemd-notices)
        run: tox run -e integration-juju-systemd-notices
