name: Release Libraries

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-libs:
    name: Release any bumped library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Release any bumped charm library
        uses: canonical/charming-actions/release-libraries@f87f8885aeb69e668b50c6c6095af5eadac457d2 # 2.2.3
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
